name: End-to-end tests

on: [push]

jobs:
  e2e-run:
    runs-on: ubuntu-latest
    name: E2E on Chrome
    strategy:
      matrix:
        node-version: [13.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn lint
      - uses: cypress-io/github-action@v1
        with:
          browser: chrome
          headless: true
          start: yarn serve
          wait-on: http://localhost:8080/
          config_file: cypress.json
          spec: "tests/e2e/**/*"
        env:
          CI: true
          CYPRESS_baseUrl: http://localhost:8080/
